import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// importing components
import busesBgImg from "../assets/images/login_images/main_schoolbuses.jpg";
import maintLogo1 from "../assets/maintLogo1.svg";
// shadcn ui
import { Input } from "../components/ui/input";
import { Button } from "../components/ui/button";
export default function SignUp() {
    return (_jsxs("section", { className: "flex justify-between", children: [_jsx("aside", { className: "flex flex-col left-0 right-0 mx-auto w-fit bottom-1/2 top-1/2 justify-center items-center z-50 absolute md:relative shadow-lg md:shadow-none bg-white", children: _jsxs("div", { className: "max-w-1/2 bg-white rounded-lg shadow-md md:shadow-none p-10", children: [_jsx("h2", { className: "text-3xl font-bold mb-8", children: "Sign up Form" }), _jsxs("form", { className: "flex flex-col w-full", children: [_jsx("label", { className: "text-sm", htmlFor: "s-username", children: "Username" }), _jsx(Input, { id: "s-username", type: "text" }), _jsx("label", { className: "mt-8 text-sm", htmlFor: "s-pw-key", children: "Password" }), _jsx(Input, { id: "s-pw-key", type: "password" }), _jsx(Button, { type: "submit", className: "w-fit mt-6", children: "Submit" })] })] }) }), _jsxs("div", { className: "bg-gradient-to-t from-emerald-600 to-emerald-400 h-screen w-full md:relative z-10 flex flex-col justify-between overflow-hidden", children: [_jsxs("div", { className: " flex flex-row-reverse justify-center items-center mt-10", children: [_jsxs("h1", { className: " drop-shadow-sm text-white z-20 relative text-center md:mt-10 text-4xl font-bold", children: ["Fleet", _jsx("span", { className: "font-light", children: "Care" }), " Pro"] }), _jsx("div", { className: "z-20 relative ", children: _jsx("img", { id: "bus-logo", className: "drop-shadow-md w-20 mr-4", src: maintLogo1, alt: "fleet care pro logo" }) })] }), _jsxs("p", { className: "text-white text-center z-20 mb-10", children: ["CCPS", " ", _jsx("span", { className: "font-light text-sm", children: "Closed Beta \u00A92025" })] }), _jsx("img", { className: "z-10 absolute blur-[1px] object-cover bottom-0 top-0 left-0 right-0 h-full w-full opacity-50 brightness-50", src: busesBgImg, alt: "fleet of buses" })] })] }));
}
