# Generated by Django 5.1.4 on 2024-12-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.IntegerField()),
                ('vin', models.CharField(max_length=17)),
                ('current_mileage', models.FloatField()),
                ('under_warranty', models.BooleanField()),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('license_plate', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'In Maintenance'), ('decommissioned', 'Decommissioned')], max_length=50)),
                ('is_down', models.BooleanField(default=False)),
                ('open_workorders', models.JSONField(default=list)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('next_service_due', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
