# Generated by Django 5.1.4 on 2024-12-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_bus_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='warranty_expiration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='current_mileage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bus',
            name='status',
            field=models.CharField(choices=[('in_service', 'In Service'), ('in_shop', 'In Shop'), ('sold', 'Sold'), ('decommissioned', 'Decommissioned')], max_length=50),
        ),
    ]
