# Generated by Django 5.1.4 on 2024-12-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_bus_warranty_expiration_alter_bus_current_mileage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='status',
            field=models.CharField(choices=[('in_service', 'In Service'), ('in_shop', 'In Shop'), ('sold', 'Sold'), ('hard_down', 'Hard Down'), ('decommissioned', 'Decommissioned')], max_length=50),
        ),
    ]
