# Generated by Django 5.1.4 on 2024-12-27 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_bus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buses', to='api.location'),
        ),
    ]
