# Generated by Django 5.1.4 on 2024-12-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_bus_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='is_down',
        ),
        migrations.AlterField(
            model_name='bus',
            name='license_plate',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='vehicle',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='vin',
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
