# Generated by Django 5.1.4 on 2024-12-27 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_bus_is_down_alter_bus_license_plate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='status',
            field=models.CharField(choices=[('in_service', 'In Service'), ('in_shop', 'In Shop'), ('sold', 'Sold'), ('hard_down', 'Hard Down'), ('decommissioned', 'Decommissioned')], default='in_service', max_length=50),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('mechanic_1', 'Mechanic I'), ('mechanic_2', 'Mechanic II'), ('mechanic_3', 'Mechanic III'), ('dispatch', 'Dispatch'), ('supervisor', 'Supervisor'), ('manager', 'Manager'), ('admin', 'Administrator')], max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('date_hired', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.bus')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='api.location')),
            ],
        ),
    ]
