# Generated by Django 5.1.4 on 2025-01-03 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_bus_status_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='assigned_bus',
            new_name='assigned_work_orders',
        ),
    ]
