# Generated by Django 5.1.4 on 2025-01-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_assigned_bus_employee_assigned_work_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='fax',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('mechanic_1', 'Mechanic I'), ('mechanic_2', 'Mechanic II'), ('mechanic_3', 'Mechanic III'), ('dispatch', 'Dispatch'), ('supervisor', 'Supervisor'), ('it_team', 'IT Team'), ('manager', 'Manager'), ('admin', 'Administrator'), ('staff', 'Staff')], max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
