# Generated by Django 5.1.4 on 2025-01-11 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_location_fax_location_phone_alter_bus_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField()),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='assigned_work_orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vehicleprofile'),
        ),
        migrations.DeleteModel(
            name='Bus',
        ),
    ]
