# Generated by Django 5.1.4 on 2025-01-11 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_vehicleprofile_alter_employee_assigned_work_orders_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vehicleprofile',
            table='vehicle_profile',
        ),
    ]
