# Generated by Django 5.1.4 on 2025-01-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_vehicleprofile_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleprofile',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='vehicleprofile',
            name='body_model',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicleprofile',
            name='bus_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vehicleprofile',
            name='veh_make',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
