# Generated by Django 5.1.4 on 2025-04-08 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_vehicleprofile_assigned_shop_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicleprofile',
            old_name='bus_no',
            new_name='veh_no',
        ),
    ]
