# Generated by Django 5.1.4 on 2025-04-08 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_bus_no_vehicleprofile_veh_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='state',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='zip',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicleprofile',
            name='current_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buses', to='api.location'),
        ),
    ]
