# Generated by Django 5.1.4 on 2025-04-09 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_workorders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkOrders',
            new_name='WorkOrder',
        ),
    ]
