# Generated by Django 5.1.4 on 2025-04-10 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_vehicleprofile_options_alter_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicleprofile',
            options={'managed': True},
        ),
    ]
