# Generated by Django 5.1.4 on 2025-04-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_vehicleprofile_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleprofile',
            name='body_no',
        ),
        migrations.RemoveField(
            model_name='vehicleprofile',
            name='month_1',
        ),
        migrations.RemoveField(
            model_name='vehicleprofile',
            name='month_10',
        ),
        migrations.RemoveField(
            model_name='vehicleprofile',
            name='month_11',
        ),
        migrations.RemoveField(
            model_name='vehicleprofile',
            name='month_12',
        ),
        migrations.RemoveField(
            model_name='vehicleprofile',
            name='month_13',
        ),
        migrations.RemoveField(
            model_name='vehicleprofile',
            name='month_2',
        ),
        migrations.RemoveField(
            model_name='vehicleprofile',
            name='month_3',
        ),
        migrations.RemoveField(
            model_name='vehicleprofile',
            name='month_4',
        ),
        migrations.RemoveField(
            model_name='vehicleprofile',
            name='month_5',
        ),
        migrations.RemoveField(
            model_name='vehicleprofile',
            name='month_6',
        ),
        migrations.RemoveField(
            model_name='vehicleprofile',
            name='month_7',
        ),
        migrations.RemoveField(
            model_name='vehicleprofile',
            name='month_8',
        ),
        migrations.RemoveField(
            model_name='vehicleprofile',
            name='month_9',
        ),
        migrations.AddField(
            model_name='vehicleprofile',
            name='inspection_due',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='assigned_shop',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='body_make',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='body_model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='body_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='bus_driver',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='cap',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='chassis_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='chassis_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='current_mileage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='eng_manuf',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='eng_model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='eng_serial_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='eng_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='fuel_gal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='gross_weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='gvw_front',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='gvw_rear',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='inservice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='insp_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='labor_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='last_fuel_mileage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='last_in_shop',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='last_oil_change',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='last_pm_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='last_pm_mileage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='last_ps_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='last_time_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='last_time_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='next_oil_change',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='next_pm_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='next_pm_mileage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='next_ps_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='orig_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='other_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='parts_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='pm_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='pm_month_1',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='pm_month_2',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='pm_month_3',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='sch_begin_mileage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='status_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='tag_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='tire_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='total_opr_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='trade_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='trans_manuf',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='trans_model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='trans_serial_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='veh_make',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='veh_model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='veh_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='vehicle_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='vin_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='wheel_base',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='wheel_chair',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='ytd_fuel',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='vehicleprofile',
            table='api_vehicleprofile',
        ),
    ]
