# Generated by Django 5.1.4 on 2025-04-10 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_vehicleprofile_body_no_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vehicleprofile',
            table='vehicle_profile',
        ),
    ]
