# Generated by Django 5.1.4 on 2025-04-10 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_vehicleprofile_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicleprofile',
            options={},
        ),
        migrations.AlterModelTable(
            name='vehicleprofile',
            table=None,
        ),
    ]
