# Generated by Django 5.1.4 on 2025-04-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_vehicleprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleprofile',
            name='inspection_due',
            field=models.DateField(blank=True, null=True),
        ),
    ]
