# Generated by Django 5.1.4 on 2025-04-10 18:00

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_vehicleprofile_inspection_due_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleprofile',
            name='inspection_due',
            field=models.DateField(blank=True, null=True),
        ),
    ]

