# Generated by Django 5.1.4 on 2025-04-10 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_add_inspection_due'),
        ('api', '0029_alter_employee_id_alter_location_city_and_more'),
    ]

    operations = [
    ]
