# Generated by Django 5.1.4 on 2025-04-10 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_merge_20250410_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleprofile',
            name='inspection_due',
        ),
    ]
