# Generated by Django 5.1.4 on 2025-04-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_remove_vehicleprofile_inspection_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleprofile',
            name='inspection_due',
            field=models.DateField(blank=True, null=True),
        ),
    ]
