# Generated by Django 5.1.4 on 2025-04-10 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_vehicleprofile_inspection_due'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleprofile',
            name='inspection_due',
        ),
    ]
