services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: levellawrence
      POSTGRES_PASSWORD: But76100
      POSTGRES_DB: fleetcarepro
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./server
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: levellawrence
      DB_PASSWORD: But76100@@
      DB_NAME: fleetcarepro
      PORT: 3000
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./client
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  pgdata:
