import { Schema, model } from "mongoose";

const vehicleSchema = new Schema(
  {
    bus_no: Number,
    veh_make: String,
    body_model: String,
    fuel_type: String,
    vin_number: String,
    tag_no: String,
    body_year: Number,
    next_ps_date: Date,
    inservice_date: Date,
    vehicle_class: String,
    month_1: Date,
    month_2: Date,
    month_3: Date,
    month_4: Date,
    month_5: Date,
    month_6: Date,
    month_7: Date,
    month_8: Date,
    month_9: Date,
    month_10: Date,
    month_11: Date,
    month_12: Date,
    month_13: Date,
    veh_model: String,
    chassis_year: Number,
    orig_cost: Number,
    cap: Number,
    body_make: String,
    body_no: Number,
    trans_serial_no: String,
    trans_manuf: String,
    trans_model: String,
    eng_type: String,
    eng_manuf: String,
    eng_model: String,
    eng_serial_no: String,
    last_in_shop: Number,
    last_ps_date: Date,
    next_oil_change: String,
    fuel_gal: Number,
    last_fuel_mileage: Number,
    ytd_fuel: Number,
    current_mileage: Number,
    sch_begin_mileage: Number,
    labor_cost: Number,
    parts_cost: Number,
    other_cost: Number,
    total_opr_cost: Number,
    chassis_no: String,
    last_time_in: Date,
    last_time_out: Date,
    last_oil_change: Number,
    status: String,
    gross_weight: Number,
    gvw_front: Number,
    tire_size: String,
    gvw_rear: Number,
    wheel_base: Number,
    wheel_chair: Boolean,
    assigned_shop: String,
    insp_group: Number,
    bus_driver: String,
    status_date: Date,
    trade_code: String,
    last_pm_mileage: Number,
    next_pm_mileage: Number,
    last_pm_date: Date,
    next_pm_date: Date,
    pm_month_1: Date,
    pm_month_2: Date,
    pm_month_3: Date,
    pm_class: String,
  },
  { collection: "Vehicles" }
);
const Vehicle = model("Vehicle", vehicleSchema);
export default Vehicle;
